Document: libtprl
Title: Debian libtprl Manual
Author: <insert document author here>
Abstract: This manual describes what libtprl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libtprl/libtprl.sgml.gz

Format: postscript
Files: /usr/share/doc/libtprl/libtprl.ps.gz

Format: text
Files: /usr/share/doc/libtprl/libtprl.text.gz

Format: HTML
Index: /usr/share/doc/libtprl/html/index.html
Files: /usr/share/doc/libtprl/html/*.html

  
